version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: host.docker.internal  # Acessa o PostgreSQL local
      DB_PORT: 5433  # Porta do PostgreSQL no seu host
      DB_USER: postgres
      DB_PASSWORD: gladson
      DB_NAME: postgres
    ports:
      - "5000:5000"
