name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./Frontend

      - name: Build the project
        run: npm run build
        working-directory: ./Frontend

      - name: Create ZIP of build folder
        run: zip -r build.zip ./Frontend/build

      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v1.0.0'
          release_name: 'Release v1.0.0'
          body: 'Release description'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v1.0.0'
          asset_path: './build.zip'
          asset_name: 'build.zip'
          asset_content_type: 'application/zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
