name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixar o repositório
      - name: Check out the repository
        uses: actions/checkout@v2

      # Passo 2: Listar os arquivos do repositório para verificar onde está o package.json
      - name: List repository contents
        run: ls -R

      # Passo 3: Configurar o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Passo 4: Instalar dependências no diretório Frontend
      - name: Install dependencies
        run: npm install --force
        working-directory: ./Frontend  # Corrigido para o diretório Frontend

      # Passo 5: Rodar o build do projeto no diretório Frontend
      - name: Build project
        run: npm run build
        working-directory: ./Frontend  # Corrigido para o diretório Frontend

      # Passo 6: Deploy para o servidor Windows utilizando SCP
      - name: Deploy to Windows server
        run: |
          scp -r ./Frontend/build/* ${WIN_SCP_USERNAME}@legaldata.mtostes.com.br:/C:/Node/
        env:
          WIN_SCP_USERNAME: ${{ secrets.WIN_SCP_USERNAME }}
          WIN_SCP_PASSWORD: ${{ secrets.WIN_SCP_PASSWORD }}
