name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixar o repositório
      - name: Check out the repository
        uses: actions/checkout@v2

      # Passo 2: Configurar o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Passo 3: Cache de dependências
      - name: Cache node_modules
        uses: actions/cache@v3  # Versão atualizada para v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Passo 4: Instalar dependências no diretório Frontend
      - name: Install dependencies
        run: npm ci --force
        working-directory: ./Frontend

      # Passo 5: Rodar o build do projeto no diretório Frontend
      - name: Build project
        run: npm run build
        working-directory: ./Frontend

      # Passo 6: Verificar o diretório de build no Frontend
      - name: Verify build directory inside Frontend
        run: ls ./Frontend/build  # Verificando dentro do diretório Frontend

      # Passo 7: Compactar o diretório build em um arquivo zip
      - name: Create build.zip
        run: |
          if [ -d "./Frontend/build" ]; then
            zip -r ./Frontend/build.zip ./Frontend/build  # Compactando o diretório build dentro do Frontend
          else
            echo "Diretório 'build' não encontrado dentro de './Frontend'!"
            exit 1
          fi
        working-directory: .  # Corrigido para garantir que o arquivo seja gerado no diretório raiz

      # Passo 8: Criar uma nova release no GitHub
      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v1.0.0'  # A tag da release
          name: 'Release v1.0.0'  # Nome da release
          body: 'Descrição da Release'
          draft: false
          prerelease: false
          files: ./Frontend/build.zip  # Arquivo a ser incluído na release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Token de autenticação para a release
