name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixar o repositório
      - name: Check out the repository
        uses: actions/checkout@v2

      # Passo 2: Listar os arquivos do repositório para verificar onde está o package.json
      - name: List repository contents
        run: ls -R

      # Passo 3: Configurar o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Passo 4: Instalar dependências (ajustado se necessário)
      - name: Install dependencies
        run: npm install  # Ajuste conforme necessário
        working-directory: ./frontend  # Ajuste o caminho do diretório, se necessário

      # Passo 5: Rodar o build do projeto
      - name: Build project
        run: npm run build

      # Passo 6: Instalar WinSCP
      - name: Install WinSCP
        run: |
          sudo apt-get update
          sudo apt-get install -y winscp

      # Passo 7: Configuração de Deploy com WinSCP
      - name: Deploy to Windows server
        run: |
          winscp.com /command "open sftp://${{ secrets.WIN_SCP_USERNAME }}:${{ secrets.WIN_SCP_PASSWORD }}@legaldata.mtostes.com.br" "put ./build/* /C:/Node/" "exit"
        env:
          WIN_SCP_PASSWORD: ${{ secrets.WIN_SCP_PASSWORD }}  # Senha do servidor Windows armazenada no GitHub Secrets
          WIN_SCP_USERNAME: ${{ secrets.WIN_SCP_USERNAME }}  # Usuário do servidor Windows armazenado no GitHub Secrets
