name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixar o repositório
      - name: Check out the repository
        uses: actions/checkout@v2

      # Passo 2: Listar os arquivos do repositório para verificar onde está o package.json
      - name: List repository contents
        run: ls -R

      # Passo 3: Configurar o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Passo 4: Instalar dependências no diretório Frontend
      - name: Install dependencies
        run: npm install --force
        working-directory: ./Frontend  # Corrigido para o diretório Frontend

      # Passo 5: Rodar o build do projeto no diretório Frontend
      - name: Build project
        run: npm run build
        working-directory: ./Frontend  # Corrigido para o diretório Frontend

      # Passo 6: Verificar o diretório de trabalho atual
      - name: Verificar diretório de trabalho atual
        run: |
          echo "Diretório atual:"
          pwd  # Verifica o diretório de trabalho atual

      # Passo 7: Verificar se o diretório 'Frontend/build' foi gerado após o build
      - name: Listar conteúdo do diretório Frontend após o build
        run: |
          echo "Conteúdo do repositório após o build:"
          ls -R ./Frontend  # Lista o conteúdo do diretório Frontend após o build

     

      # Passo 9: Compactar o diretório build em um arquivo zip
      - name: Create build.zip
        run: |
          if [ -d "./Frontend/build" ]; then
            zip -r ./Frontend/build.zip ./Frontend/build
          else
            echo "Diretório 'build' não encontrado!"
            exit 1
          fi
        working-directory: ./Frontend  # Certifique-se de que o arquivo build.zip será gerado corretamente

         # Passo 8: Verificar a existência do arquivo build.zip
      - name: Verificar a existência do build.zip
        run: |
          echo "Verificando se o arquivo build.zip existe:"
          ls ./Frontend/build.zip  # Verifica se o arquivo build.zip foi gerado no diretório correto

      # Passo 10: Criar uma nova release no GitHub
      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v1.0.0'  # A tag da release
          release_name: 'Release v1.0.0'
          body: 'Descrição da Release'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # Passo 11: Fazer o upload do build para a release criada
      - name: Upload Build to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v1.0.0'
          asset_path: './Frontend/build.zip'  # Caminho para o arquivo gerado
          asset_name: 'build.zip'
          asset_content_type: 'application/zip'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
