name: Deploy Automático no Servidor

on:
  push:
    branches:
      - main  # Vai rodar quando houver um push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out do código
        uses: actions/checkout@v2

      - name: Conectar ao Servidor via SSH e Executar Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}  # URL do seu servidor
          username: ${{ secrets.SSH_USER }}  # Usuário SSH
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Chave privada SSH
          script: |
            # Navega até o diretório do projeto
            cd /home/ubuntu/Docker

            # Puxa as últimas alterações do repositório
            git pull origin main

            # Parar e remover containers existentes
            docker-compose down

            # Reconstruir e iniciar somente o serviço 'docker_frontend'
            # docker-compose up -d --build frontend

            # Reiniciar os outros serviços sem rebuild
            docker-compose up -d
