name: Deploy Automático no Servidor

on:
  push:
    branches:
      - main  # Vai rodar quando houver um push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out do código
        uses: actions/checkout@v2

      - name: Conectar ao Servidor via SSH e Executar Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}  # Esse valor é a URL do seu servidor
          username: ${{ secrets.SSH_USER }}  # Esse valor é o usuário SSH
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Aqui vai a chave privada SSH
          script: |
            # Navega até o diretório do projeto
            cd /Docker

            # Parar e remover containers existentes
            docker-compose down

            # Puxa as últimas alterações do repositório
            git pull origin main

            # Construa e inicie os containers Docker
            docker-compose up -d --build
